apiVersion: v1
kind: Service
metadata:
  name: liveandready
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: liveandready
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liveandready
  name: liveandready
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: liveandready
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: liveandready
    spec:
      containers:
      - image: nginxdemos/hello:plain-text
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 1
        name: hello
        resources: {}
        command:
        - /bin/sh
        - '-c'
        - ' if [ `od -An -N1 -i /dev/urandom` -gt 50 ]; then echo "I am broken" && sleep 100000; else nginx -g "daemon off;"; fi'
      restartPolicy: Always
      terminationGracePeriodSeconds: 5

