apiVersion: v1
kind: Pod
metadata:
  name: second
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the other container > /pod-data/index.html; sleep 3600"]
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

