apiVersion: v1
kind: Service
metadata:
  name: emptydir
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: emptydir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emptydir
  name: emptydir
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emptydir
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: emptydir
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test
      - image: ubuntu
        volumeMounts:
        - mountPath: /busy
          name: test
        name: ubuntu
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
        - sh
        - -c
        - chmod 777 /busy && echo "$MY_POD_NAMESPACE - $MY_NODE_NAME - $MY_POD_NAME" >> /busy/index.html  && while true; do sleep 1 && date; done
      restartPolicy: Always
      terminationGracePeriodSeconds: 3
      volumes:
       - name: test
         emptyDir: {} 
